const nodemailer = require('nodemailer');

// Generate random 6-digit OTP
const generateOTP = () => {
    return Math.floor(100000 + Math.random() * 900000).toString();
};

// Create email transporter
const createTransporter = () => {
    return nodemailer.createTransport({
        service: 'gmail',
        host: 'smtp.gmail.com',
        port: 465,
        secure: true, // Use SSL
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS
        },
        tls: {
            rejectUnauthorized: false // Helps with some local development issues
        }
    });
};

// Send verification email with OTP
const sendVerificationEmail = async (email, code) => {
    const transporter = createTransporter();

    const mailOptions = {
        from: `"Solo Leveling System" <${process.env.EMAIL_USER}>`,
        to: email,
        subject: '🎮 Your Hunter Verification Code',
        html: `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body {
                        font-family: 'Arial', sans-serif;
                        background-color: #0a0e27;
                        color: #ffffff;
                        margin: 0;
                        padding: 0;
                    }
                    .container {
                        max-width: 600px;
                        margin: 40px auto;
                        background: linear-gradient(135deg, #1a1f3a 0%, #0a0e27 100%);
                        border: 2px solid #00eaff;
                        border-radius: 10px;
                        padding: 40px;
                        box-shadow: 0 0 30px rgba(0, 234, 255, 0.3);
                    }
                    .header {
                        text-align: center;
                        margin-bottom: 30px;
                    }
                    .title {
                        color: #00eaff;
                        font-size: 28px;
                        font-weight: bold;
                        text-transform: uppercase;
                        letter-spacing: 2px;
                        margin: 0;
                        text-shadow: 0 0 10px rgba(0, 234, 255, 0.5);
                    }
                    .subtitle {
                        color: #a0a0a0;
                        font-size: 14px;
                        margin-top: 5px;
                    }
                    .content {
                        text-align: center;
                        margin: 30px 0;
                    }
                    .message {
                        color: #e0e0e0;
                        font-size: 16px;
                        line-height: 1.6;
                        margin-bottom: 30px;
                    }
                    .otp-box {
                        background: rgba(0, 234, 255, 0.1);
                        border: 2px solid #00eaff;
                        border-radius: 8px;
                        padding: 20px;
                        margin: 20px 0;
                    }
                    .otp-code {
                        font-size: 42px;
                        font-weight: bold;
                        color: #00eaff;
                        letter-spacing: 8px;
                        margin: 10px 0;
                        text-shadow: 0 0 15px rgba(0, 234, 255, 0.6);
                    }
                    .expiry {
                        color: #ff6b6b;
                        font-size: 14px;
                        margin-top: 15px;
                    }
                    .footer {
                        text-align: center;
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #333;
                        color: #666;
                        font-size: 12px;
                    }
                    .warning {
                        background: rgba(255, 107, 107, 0.1);
                        border-left: 3px solid #ff6b6b;
                        padding: 15px;
                        margin-top: 20px;
                        font-size: 13px;
                        color: #ffb3b3;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1 class="title">⚔️ SYSTEM ⚔️</h1>
                        <p class="subtitle">Hunter Registry Verification</p>
                    </div>
                    
                    <div class="content">
                        <p class="message">
                            Greetings, Hunter.<br><br>
                            Your verification code has been generated by the System.
                        </p>
                        
                        <div class="otp-box">
                            <div class="otp-code">${code}</div>
                            <p class="expiry">⏱️ Expires in 5 minutes</p>
                        </div>
                        
                        <p class="message">
                            Enter this code to complete your registration and awaken your abilities.
                        </p>
                        
                        <div class="warning">
                            ⚠️ If you did not request this code, please ignore this email. Never share your verification code with anyone.
                        </div>
                    </div>
                    
                    <div class="footer">
                        <p>This is an automated message from the Solo Leveling System.</p>
                        <p>Do not reply to this email.</p>
                    </div>
                </div>
            </body>
            </html>
        `
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log('✅ Verification email sent:', info.messageId);
        return { success: true, messageId: info.messageId };
    } catch (error) {
        console.error('❌ Email send error:', error);
        throw new Error('Failed to send verification email');
    }
};

module.exports = {
    generateOTP,
    sendVerificationEmail
};
